/*-
 * Copyright (c) 2016-2019, F5 Networks, Inc.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *    http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package as3

import (
	"encoding/json"
	"io/ioutil"
	"net/http"
	"time"

	// "github.com/F5Networks/k8s-bigip-ctlr/pkg/postmanager"
	// "github.com/F5Networks/k8s-bigip-ctlr/pkg/postmanager"
	. "github.com/F5Networks/k8s-bigip-ctlr/pkg/resource"
	log "github.com/F5Networks/k8s-bigip-ctlr/pkg/vlogger"
	routeclient "github.com/openshift/client-go/route/clientset/versioned/typed/route/v1"
	//routeapi "github.com/openshift/api/route/v1"
)

const (
	defaultAS3ConfigMapLabel = "f5type in (virtual-server), as3 in (true)"
	svcTenantLabel           = "cis.f5.com/as3-tenant"
	svcAppLabel              = "cis.f5.com/as3-app"
	svcPoolLabel             = "cis.f5.com/as3-pool"
	baseAS3Config            = `{
  "$schema": "https://raw.githubusercontent.com/F5Networks/f5-appsvcs-extension/master/schema/3.18.0/as3-schema-3.18.0-4.json",
  "class": "AS3",
  "declaration": {
    "class": "ADC",
    "schemaVersion": "3.18.0",
    "id": "urn:uuid:B97DFADF-9F0D-4F6C-8D66-E9B52E593694",
    "label": "CIS Declaration",
    "remark": "Auto-generated by CIS",
    "controls": {
       "class": "Controls",
       "userAgent": "CIS Configured AS3"
    }
  }
}
`
	as3tenant            = "Tenant"
	as3class             = "class"
	as3SharedApplication = "Shared"
	as3application       = "Application"
	as3shared            = "shared"
	as3template          = "template"
	// Constants for Resource Types
	resourceTypeIngress string = "ingress"
	resourceTypeRoute   string = "route"
	//resourceTypeCfgMap string = "cfgMap"
	oprTypeCreate      = "create"
	oprTypeUpdate      = "update"
	oprTypeDelete      = "delete"
	as3SchemaLatestURL = "https://raw.githubusercontent.com/F5Networks/f5-appsvcs-extension/master/schema/latest/as3-schema.json"
	as3SchemaFileName  = "as3-schema-3.18.0-4-cis.json"
)

// TODO SNATRA Remove TEMORARY VARIABLE
type endPoints struct {
	members []Member
}

type AgentRequestConfig struct {
	PoolMembers    map[string]endPoints
	resources      *Resources
	customProfiles *CustomProfileStore
	irulesMap      IRulesMap
	intDgMap       InternalDataGroupMap
	intF5Res       InternalF5ResourcesGroup
}

// AS3Config consists of all the AS3 related configurations
type AS3Config struct {
	as3RsrcType        string
	adc                as3ADC
	configmap          AS3ConfigMap
	overrideConfigmap  AS3ConfigMap
	unifiedDeclaration as3Declaration
}

// ActiveAS3ConfigMap user defined ConfigMap for global availability.
type AS3ConfigMap struct {
	Name      string         // AS3 specific ConfigMap name
	Namespace string         // AS3 specific ConfigMap namespace
	OprType   string         // Operations like create/update/delete
	State     int            // State of the configMap
	cfg       string         // configuration in combination of "name/namespace" of cfgMap
	tmpData   string         // Holds AS3 template received from cfgMap resource.
	Data      as3Declaration // if AS3 Name is present, populate this with AS3 template data.
}

// AS3AS3Manager holds all the AS3 orchestration specific Data
type AS3Manager struct {
	Agent                     string // TODO SNATRA Remove this
	as3Members                map[Member]struct{}
	as3Validation             bool
	sslInsecure               bool
	enableTLS                 string
	tls13CipherGroupReference string
	ciphers                   string
	// Active User Defined ConfigMap details
	as3ActiveConfig AS3Config
	// List of Watched Endpoints for user-defined AS3
	watchedAS3Endpoints map[string]struct{}
	// Watched namespaces
	// WatchedNS                 WatchedNamespaces
	As3SchemaLatest string
	// Override existing as3 declaration with this configmap
	OverrideAS3Decl string
	// User defined AS3 declaration
	UserDefinedAS3Decl string
	// Path of schemas reside locally
	SchemaLocalPath string
	// Flag to check schema validation using reference or string
	As3SchemaFlag bool
	// Processed routes for updating Admit Status
	// RoutesProcessed           RouteMap TODO this will move to CIS Core
	// POSTs configuration to BIG-IP using AS3
	PostManager *PostManager
	// To put list of tenants in BIG-IP REST call URL that are in AS3 declaration
	FilterTenants    bool
	DefaultPartition string
	ReqChan          chan MessageRequest
	RspChan          chan interface{}
	ResourceRequest
	//CISAgentRsp
	// postmanager.Params
	//AgentRequestConfig // This is a temporary

}

// Struct to allow NewManager to receive all or only specific parameters.
type Params struct {
	// Package local for unit testing only
	Agent                     string // TODO SNATRA Remove this
	SchemaLocal               string
	AS3Validation             bool
	SSLInsecure               bool
	EnableTLS                 string
	TLS13CipherGroupReference string
	Ciphers                   string
	//Agent                     string
	OverrideAS3Decl    string
	UserDefinedAS3Decl string
	SchemaLocalPath    string
	FilterTenants      bool
	BIGIPUsername      string
	BIGIPPassword      string
	BIGIPURL           string
	TrustedCerts       string
	AS3PostDelay       int
	//Log the AS3 response body in Controller logs
	LogResponse   bool
	RouteClientV1 routeclient.RouteV1Interface
	RspChan       chan interface{}
}

// Create and return a new app manager that meets the Manager interface
func NewAS3Manager(params *Params) *AS3Manager {
	AS3Manager := AS3Manager{
		as3Members:                make(map[Member]struct{}, 0),
		as3Validation:             params.AS3Validation,
		sslInsecure:               params.SSLInsecure,
		enableTLS:                 params.EnableTLS,
		tls13CipherGroupReference: params.TLS13CipherGroupReference,
		ciphers:                   params.Ciphers,
		//OverrideAS3Decl:    params.OverrideAS3Decl,
		//UserDefinedAS3Decl: ,
		SchemaLocalPath: params.SchemaLocal,
		FilterTenants:   params.FilterTenants,
		//ReqChan:         make(chan MessageRequest, 1),
		RspChan: params.RspChan,
		as3ActiveConfig: AS3Config{
			configmap:         AS3ConfigMap{cfg: params.OverrideAS3Decl},
			overrideConfigmap: AS3ConfigMap{cfg: params.UserDefinedAS3Decl},
		},
		PostManager: NewPostManager(PostParams{
			BIGIPUsername: params.BIGIPUsername,
			BIGIPPassword: params.BIGIPPassword,
			BIGIPURL:      params.BIGIPURL,
			TrustedCerts:  params.TrustedCerts,
			SSLInsecure:   params.SSLInsecure,
			AS3PostDelay:  params.AS3PostDelay,
			LogResponse:   params.LogResponse}),
	}
	return &AS3Manager
}

func (as3Mgr *AS3Manager) postAS3Declaration(rsReq ResourceRequest) (bool, string) {

	as3Mgr.ResourceRequest = rsReq

	as3Config := AS3Config{}
	if as3Mgr.ResourceRequest.PoolMembers != nil {
		// Process ConfigMaps TODO cfgMap implementation
		as3Config = as3Mgr.as3ActiveConfig
	} else {
		// Process Route or Ingress
		as3Config = as3Mgr.prepareAS3ResourceConfig()
	}

	return as3Mgr.postAS3Config(as3Config)
}

func (as3Mgr *AS3Manager) postAS3Config(tempAS3Config AS3Config) (bool, string) {
	unifiedDecl := tempAS3Config.getUnifiedDeclaration()
	if unifiedDecl == "" {
		return true, ""
	}

	if ok := as3Mgr.validateAS3Template(string(unifiedDecl)); !ok {
		log.Errorf("[AS3] Error in validating declaration  !!!!!! %v", string(unifiedDecl))
		return true, ""
	}

	if DeepEqualJSON(as3Mgr.as3ActiveConfig.unifiedDeclaration, unifiedDecl) {
		log.Debug("[AS3] No Change in the Configuration")
		return true, ""
	}

	as3Mgr.as3ActiveConfig.updateConfig(tempAS3Config)

	var tenants []string = nil

	if as3Mgr.FilterTenants {
		tenants = getTenants(unifiedDecl)
	}

	return as3Mgr.PostManager.postConfig(string(unifiedDecl), tenants)
}

func (cfg *AS3Config) updateConfig(newAS3Cfg AS3Config) {
	cfg.configmap.Data = newAS3Cfg.configmap.Data
	cfg.adc = newAS3Cfg.adc
	cfg.overrideConfigmap.Data = newAS3Cfg.overrideConfigmap.Data
	cfg.unifiedDeclaration = newAS3Cfg.unifiedDeclaration
}

func (cfg *AS3Config) getUnifiedDeclaration() as3Declaration {
	if cfg.adc == nil && cfg.configmap.Data == "" {
		return ""
	}

	// Need to process Routes
	var as3Config map[string]interface{}
	if cfg.configmap.Data != "" {
		// Merge activeCfgMap and as3RouteCfg
		_ = json.Unmarshal([]byte(cfg.configmap.Data), &as3Config)
	} else {
		// Merge base AS3 template and as3RouteCfg
		_ = json.Unmarshal([]byte(baseAS3Config), &as3Config)
	}

	if cfg.adc != nil {
		adc, _ := as3Config["declaration"].(map[string]interface{})

		for k, v := range cfg.adc {
			adc[k] = v
		}
	}

	unifiedDecl, err := json.Marshal(as3Config)
	if err != nil {
		log.Debugf("[AS3] Unified declaration: %v\n", err)
	}

	if string(cfg.overrideConfigmap.Data) == "" {
		cfg.unifiedDeclaration = as3Declaration(unifiedDecl)
		return as3Declaration(unifiedDecl)
	}

	overriddenUnifiedDecl := ValidateAndOverrideAS3JsonData(string(cfg.overrideConfigmap.Data),
		string(unifiedDecl))
	if overriddenUnifiedDecl == "" {
		log.Debug("[AS3] Failed to override AS3 Declaration")
		cfg.overrideConfigmap.errorState()
		cfg.unifiedDeclaration = as3Declaration(unifiedDecl)
		return as3Declaration(unifiedDecl)
	}
	cfg.overrideConfigmap.activeState()
	cfg.unifiedDeclaration = as3Declaration(overriddenUnifiedDecl)
	return as3Declaration(overriddenUnifiedDecl)
}

func (as3Mgr *AS3Manager) DeleteAS3Partition(partition string) {
	var as3Config map[string]interface{}
	_ = json.Unmarshal([]byte(baseAS3Config), &as3Config)
	decl := as3Config["declaration"].(map[string]interface{})
	decl[partition] = map[string]string{"class": "Tenant"}
	data, _ := json.Marshal(as3Config)

	tempAS3Config := as3Mgr.as3ActiveConfig
	tempAS3Config.configmap.Data = as3Declaration(data)
	as3Mgr.postAS3Config(tempAS3Config)
}

func (c AS3Config) Init(partition string) {
	c.adc.initDefault(partition)
	c.configmap.reset()
	c.overrideConfigmap.reset()
}

func (as3Mgr *AS3Manager) FetchAS3Schema() error {

	res, err := http.Get(as3SchemaLatestURL)
	if err != nil {
		log.Debugf("Error while fetching latest as3 schema : %v", err)
		as3Mgr.fallbackToLocalAS3Schema()
		return err
	}
	if res.StatusCode == http.StatusOK {
		body, err := ioutil.ReadAll(res.Body)
		if err != nil {
			log.Debugf("Unable to read the as3 template from json response body : %v", err)
			as3Mgr.fallbackToLocalAS3Schema()
			return err
		}
		defer res.Body.Close()

		jsonMap := make(map[string]interface{})
		err = json.Unmarshal(body, &jsonMap)
		if err != nil {
			log.Debugf("Unable to unmarshal json response body : %v", err)
			as3Mgr.fallbackToLocalAS3Schema()
			return err
		}

		jsonMap["$id"] = as3SchemaLatestURL
		byteJSON, err := json.Marshal(jsonMap)
		if err != nil {
			log.Debugf("Unable to marshal : %v", err)
			as3Mgr.fallbackToLocalAS3Schema()
			return err
		}
		as3Mgr.As3SchemaLatest = string(byteJSON)
		return nil
	}
	as3Mgr.fallbackToLocalAS3Schema()
	return nil
}

func (as3Mgr *AS3Manager) fallbackToLocalAS3Schema() {
	as3Mgr.As3SchemaFlag = true
	log.Debugf("Unable to fetch the latest AS3 schema : validating AS3 schema with %v", as3SchemaFileName)
	as3Mgr.As3SchemaLatest = as3Mgr.SchemaLocalPath + as3SchemaFileName
	return
}

// configWorker blocks on postChan
// whenever gets unblocked posts active configuration to BIG-IP
func (as3Mgr *AS3Manager) ConfigDeployer() {
	// For the very first post after starting controller, need not wait to post
	firstPost := true
	for msgReq := range as3Mgr.ReqChan {
		if !firstPost && as3Mgr.PostManager.AS3PostDelay != 0 {
			// Time (in seconds) that CIS waits to post the AS3 declaration to BIG-IP.
			log.Debugf("[AS3] Delaying post to BIG-IP for %v seconds", as3Mgr.PostManager.AS3PostDelay)
			_ = <-time.After(time.Duration(as3Mgr.PostManager.AS3PostDelay) * time.Second)
		}

		// After postDelay expires pick up latest declaration, if available
		select {
		case msgReq = <-as3Mgr.ReqChan:
		case <-time.After(1 * time.Microsecond):
		}

		log.Debugf("[AS3] Posting AS3 Decleration")
		posted, event := as3Mgr.postAS3Declaration(msgReq.ResourceRequest)
		// To handle general errors
		for !posted {
			timeout := getTimeDurationForErrorResponse(event)
			log.Debugf("[AS3] Error handling for event %v", event)
			posted, event = as3Mgr.postOnEventOrTimeout(timeout)
		}
		firstPost = false
		log.Debugf("[AS3] Successful Event %v", event)
		if event == responseStatusOk {
			log.Debugf("[AS3] Preparing response message to response handler")
			agRsp := MessageResponse{}
			agRsp.ReqID = msgReq.ReqID
			agRsp.AdmitStatus = true
			select {
			case as3Mgr.RspChan <- agRsp:
			case <-as3Mgr.RspChan:
				as3Mgr.RspChan <- agRsp
			}
			log.Debugf("[AS3] Sent response message to response handler %v", as3Mgr.RspChan)
		}
	}
}

func (as3Mgr *AS3Manager) postOnEventOrTimeout(timeout time.Duration) (bool, string) {
	select {
	case msgReq := <-as3Mgr.ReqChan:
		return as3Mgr.postAS3Declaration(msgReq.ResourceRequest)
	case <-time.After(timeout):
		tenants := getTenants(as3Mgr.as3ActiveConfig.unifiedDeclaration)
		unifiedDeclaration := string(as3Mgr.as3ActiveConfig.unifiedDeclaration)
		return as3Mgr.PostManager.postConfig(unifiedDeclaration, tenants)
	}
}
