/*-
 * Copyright (c) 2016-2019, F5 Networks, Inc.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *    http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package as3

import (
	"encoding/json"
	"io/ioutil"
	"net/http"
	"time"

	. "github.com/F5Networks/k8s-bigip-ctlr/pkg/resource"
	log "github.com/F5Networks/k8s-bigip-ctlr/pkg/vlogger"
)

const (
	defaultAS3ConfigMapLabel = "f5type in (virtual-server), as3 in (true)"
	svcTenantLabel           = "cis.f5.com/as3-tenant"
	svcAppLabel              = "cis.f5.com/as3-app"
	svcPoolLabel             = "cis.f5.com/as3-pool"
	baseAS3Config            = `{
  "$schema": "https://raw.githubusercontent.com/F5Networks/f5-appsvcs-extension/master/schema/3.18.0/as3-schema-3.18.0-4.json",
  "class": "AS3",
  "declaration": {
    "class": "ADC",
    "schemaVersion": "3.18.0",
    "id": "urn:uuid:B97DFADF-9F0D-4F6C-8D66-E9B52E593694",
    "label": "CIS Declaration",
    "remark": "Auto-generated by CIS",
    "controls": {
       "class": "Controls",
       "userAgent": "CIS Configured AS3"
    }
  }
}
`
	as3tenant            = "Tenant"
	as3class             = "class"
	as3SharedApplication = "Shared"
	as3application       = "Application"
	as3shared            = "shared"
	as3template          = "template"
	as3SchemaLatestURL   = "https://raw.githubusercontent.com/F5Networks/f5-appsvcs-extension/master/schema/latest/as3-schema.json"
	as3SchemaFileName    = "as3-schema-3.18.0-4-cis.json"
)

// AS3Config consists of all the AS3 related configurations
type AS3Config struct {
	as3RsrcType        string
	adc                as3ADC
	configmap          AS3ConfigMap
	overrideConfigmap  AS3ConfigMap
	unifiedDeclaration as3Declaration
}

// ActiveAS3ConfigMap user defined ConfigMap for global availability.
type AS3ConfigMap struct {
	Name      string         // AS3 specific ConfigMap name
	Namespace string         // AS3 specific ConfigMap namespace
	State     int            // State of the configMap
	cfg       string         // configuration in combination of "name/namespace" of cfgMap
	tmpData   string         // Holds AS3 template received from cfgMap resource.
	Data      as3Declaration // if AS3 Name is present, populate this with AS3 template data.
}

// AS3AS3Manager holds all the AS3 orchestration specific Data
type AS3Manager struct {
	as3Validation             bool
	sslInsecure               bool
	enableTLS                 string
	tls13CipherGroupReference string
	ciphers                   string
	// Active User Defined ConfigMap details
	as3ActiveConfig AS3Config
	As3SchemaLatest string
	// Override existing as3 declaration with this configmap
	OverrideAS3Decl string
	// User defined AS3 declaration
	UserDefinedAS3Decl string
	// Path of schemas reside locally
	SchemaLocalPath string
	// Flag to check schema validation using reference or string
	As3SchemaFlag bool
	// Processed routes for updating Admit Status
	// RoutesProcessed           RouteMap TODO this will move to CIS Core
	// POSTs configuration to BIG-IP using AS3
	PostManager *PostManager
	// To put list of tenants in BIG-IP REST call URL that are in AS3 declaration
	FilterTenants    bool
	DefaultPartition string
	ReqChan          chan MessageRequest
	RspChan          chan interface{}
	ResourceRequest
	ResourceResponse
}

// Struct to allow NewManager to receive all or only specific parameters.
type Params struct {
	// Package local for unit testing only
	SchemaLocal               string
	AS3Validation             bool
	SSLInsecure               bool
	EnableTLS                 string
	TLS13CipherGroupReference string
	Ciphers                   string
	//Agent                     string
	OverrideAS3Decl    string
	UserDefinedAS3Decl string
	SchemaLocalPath    string
	FilterTenants      bool
	BIGIPUsername      string
	BIGIPPassword      string
	BIGIPURL           string
	TrustedCerts       string
	AS3PostDelay       int
	//Log the AS3 response body in Controller logs
	LogResponse   bool
	RspChan       chan interface{}
}

// Create and return a new app manager that meets the Manager interface
func NewAS3Manager(params *Params) *AS3Manager {
	AS3Manager := AS3Manager{
		as3Validation:             params.AS3Validation,
		sslInsecure:               params.SSLInsecure,
		enableTLS:                 params.EnableTLS,
		tls13CipherGroupReference: params.TLS13CipherGroupReference,
		ciphers:                   params.Ciphers,
		SchemaLocalPath: params.SchemaLocal,
		FilterTenants:   params.FilterTenants,
		RspChan: params.RspChan,
		as3ActiveConfig: AS3Config{
			configmap:         AS3ConfigMap{cfg: params.UserDefinedAS3Decl},
			overrideConfigmap: AS3ConfigMap{cfg: params.OverrideAS3Decl},
		},
		PostManager: NewPostManager(PostParams{
			BIGIPUsername: params.BIGIPUsername,
			BIGIPPassword: params.BIGIPPassword,
			BIGIPURL:      params.BIGIPURL,
			TrustedCerts:  params.TrustedCerts,
			SSLInsecure:   params.SSLInsecure,
			AS3PostDelay:  params.AS3PostDelay,
			LogResponse:   params.LogResponse}),
	}

	AS3Manager.as3ActiveConfig.overrideConfigmap.Init()
	AS3Manager.as3ActiveConfig.configmap.Init()

	return &AS3Manager
}

func (am *AS3Manager) postAS3Declaration(rsReq ResourceRequest) (bool, string) {

	am.ResourceRequest = rsReq

	as3Config := AS3Config{}
	if am.ResourceRequest.AgentCfgmap != nil {
		for _, cfgMap := range am.ResourceRequest.AgentCfgmap{
			am.processAS3ConfigMap(*cfgMap)
		}
	}
	// Process Route or Ingress
	as3Config = am.prepareAS3ResourceConfig()

	return am.postAS3Config(as3Config)
}

func (am *AS3Manager) postAS3Config(tempAS3Config AS3Config) (bool, string) {
	unifiedDecl := tempAS3Config.getUnifiedDeclaration()
	if unifiedDecl == "" {
		return true, ""
	}

	if DeepEqualJSON(am.as3ActiveConfig.unifiedDeclaration, unifiedDecl) {
		return true, ""
	}

	if ok := am.validateAS3Template(string(unifiedDecl)); !ok {
		return true, ""
	}

	log.Debugf("[AS3] Posting AS3 Declaration")

	am.sendFDBRecords()

	am.as3ActiveConfig.updateConfig(tempAS3Config)

	var tenants []string = nil

	if am.FilterTenants {
		tenants = getTenants(unifiedDecl)
	}

	return am.PostManager.postConfig(string(unifiedDecl), tenants)
}

func (cfg *AS3Config) updateConfig(newAS3Cfg AS3Config) {
	cfg.configmap.Data = newAS3Cfg.configmap.Data
	cfg.adc = newAS3Cfg.adc
	cfg.overrideConfigmap.Data = newAS3Cfg.overrideConfigmap.Data
	cfg.unifiedDeclaration = newAS3Cfg.unifiedDeclaration
}

func (cfg *AS3Config) getUnifiedDeclaration() as3Declaration {
	if cfg.adc == nil && cfg.configmap.Data == "" {
		return ""
	}

	// Need to process Routes
	var as3Config map[string]interface{}
	if cfg.configmap.Data != "" {
		// Merge activeCfgMap and as3RouteCfg
		_ = json.Unmarshal([]byte(cfg.configmap.Data), &as3Config)
	} else {
		// Merge base AS3 template and as3RouteCfg
		_ = json.Unmarshal([]byte(baseAS3Config), &as3Config)
	}

	if cfg.adc != nil {
		adc, _ := as3Config["declaration"].(map[string]interface{})

		for k, v := range cfg.adc {
			adc[k] = v
		}
	}

	unifiedDecl, err := json.Marshal(as3Config)
	if err != nil {
		log.Debugf("[AS3] Unified declaration: %v\n", err)
	}

	if string(cfg.overrideConfigmap.Data) == "" {
		cfg.unifiedDeclaration = as3Declaration(unifiedDecl)
		return as3Declaration(unifiedDecl)
	}

	overriddenUnifiedDecl := ValidateAndOverrideAS3JsonData(string(cfg.overrideConfigmap.Data),
		string(unifiedDecl))
	if overriddenUnifiedDecl == "" {
		log.Debug("[AS3] Failed to override AS3 Declaration")
		cfg.overrideConfigmap.errorState()
		cfg.unifiedDeclaration = as3Declaration(unifiedDecl)
		return as3Declaration(unifiedDecl)
	}
	cfg.overrideConfigmap.activeState()
	cfg.unifiedDeclaration = as3Declaration(overriddenUnifiedDecl)
	return as3Declaration(overriddenUnifiedDecl)
}

func (am *AS3Manager) DeleteAS3Partition(partition string) {
	var as3Config map[string]interface{}
	_ = json.Unmarshal([]byte(baseAS3Config), &as3Config)
	decl := as3Config["declaration"].(map[string]interface{})
	decl[partition] = map[string]string{"class": "Tenant"}
	data, _ := json.Marshal(as3Config)

	tempAS3Config := am.as3ActiveConfig
	tempAS3Config.configmap.Data = as3Declaration(data)
	am.postAS3Config(tempAS3Config)
}

func (c AS3Config) Init(partition string) {
	c.adc.initDefault(partition)
	c.configmap.Init()
	c.overrideConfigmap.Init()
}

func (am *AS3Manager) FetchAS3Schema() error {
	defer am.fallbackToLocalAS3Schema()
	res, err := http.Get(as3SchemaLatestURL)
	if err != nil {
		log.Debugf("Error while fetching latest as3 schema : %v", err)
		return err
	}
	if res.StatusCode == http.StatusOK {
		body, err := ioutil.ReadAll(res.Body)
		if err != nil {
			log.Debugf("Unable to read the as3 template from json response body : %v", err)
			return err
		}
		defer res.Body.Close()

		jsonMap := make(map[string]interface{})
		err = json.Unmarshal(body, &jsonMap)
		if err != nil {
			log.Debugf("Unable to unmarshal json response body : %v", err)
			return err
		}

		jsonMap["$id"] = as3SchemaLatestURL
		byteJSON, err := json.Marshal(jsonMap)
		if err != nil {
			log.Debugf("Unable to marshal : %v", err)
			return err
		}
		am.As3SchemaLatest = string(byteJSON)
		return nil
	}
	return nil
}

func (am *AS3Manager) fallbackToLocalAS3Schema() {
	am.As3SchemaFlag = true
	log.Debugf("Unable to fetch the latest AS3 schema : validating AS3 schema with %v", as3SchemaFileName)
	am.As3SchemaLatest = am.SchemaLocalPath + as3SchemaFileName
	return
}

// configWorker blocks on postChan
// whenever gets unblocked posts active configuration to BIG-IP
func (am *AS3Manager) ConfigDeployer() {
	// For the very first post after starting controller, need not wait to post
	firstPost := true
	for msgReq := range am.ReqChan {
		if !firstPost && am.PostManager.AS3PostDelay != 0 {
			// Time (in seconds) that CIS waits to post the AS3 declaration to BIG-IP.
			log.Debugf("[AS3] Delaying post to BIG-IP for %v seconds", am.PostManager.AS3PostDelay)
			_ = <-time.After(time.Duration(am.PostManager.AS3PostDelay) * time.Second)
		}

		// After postDelay expires pick up latest declaration, if available
		select {
		case msgReq = <-am.ReqChan:
		case <-time.After(1 * time.Microsecond):
		}

		posted, event := am.postAS3Declaration(msgReq.ResourceRequest)
		// To handle general errors
		for !posted {
			timeout := getTimeDurationForErrorResponse(event)
			log.Debugf("[AS3] Error handling for event %v", event)
			posted, event = am.postOnEventOrTimeout(timeout)
		}
		firstPost = false
		if event == responseStatusOk {
			log.Debugf("[AS3] Preparing response message to response handler")
			agRsp := am.ResourceResponse
			agRsp.AdmitStatus = true
			select {
			case am.RspChan <- agRsp:
			case <-am.RspChan:
				am.RspChan <- agRsp
			}
			log.Debugf("[AS3] Sent response message to response handler %v", am.RspChan)
		}
	}
}

func (am *AS3Manager) postOnEventOrTimeout(timeout time.Duration) (bool, string) {
	select {
	case msgReq := <-am.ReqChan:
		return am.postAS3Declaration(msgReq.ResourceRequest)
	case <-time.After(timeout):
		tenants := getTenants(am.as3ActiveConfig.unifiedDeclaration)
		unifiedDeclaration := string(am.as3ActiveConfig.unifiedDeclaration)
		return am.PostManager.postConfig(unifiedDeclaration, tenants)
	}
}

func isValidAS3CfgMap(labels map[string]string) (string, bool) {
	if val, ok := labels["f5type"]; ok && val == "virtual-server" {
		if val, ok := labels["overrideAS3"]; ok && val == "true" {
			return "overrideAS3", true
		} else if val, ok := labels["as3"]; ok && val == "true" {
			return "as3", true
		}
	}
	return "", false
}
func (am *AS3Manager) sendFDBRecords(){
	agRsp := ResourceResponse{}
	agRsp.FdbRecords = true
	select {
	case am.RspChan <- agRsp:
	case <-am.RspChan:
		am.RspChan <- agRsp
	}
}

